### ISSUE TITLE
In Go 1.21 and later, the way `map` is printed is different.

### ISSUE THREAD

**Issue by smc0210** [portone-io/gophplib#19]
If you run the code below on go1.20 and 1.21 and above respectively, you can see that the results are different.  
As you can see, even though it's a simple code that initialize `map` and simply prints it, the result is always the same, and it varies between versions.

```go
map_parsestr := gophplib.ParseStr("arr[]=A&arr[]=B&arr[9]=C&arr[]=D&arr[foo]=E&arr[]=F&arr[15.1]=G&arr[]=H")
fmt.Println(map_parsestr)

init_map := map[any]any{
	"arr": map[any]any{            
		0:      "A",
		1:      "B",
		9:      "C",
		10:     "D",
		"foo":  "E",
		11:     "F",
		"15.1": "G",
		12:     "H",
	},
}
fmt.Println(init_map)
```
<img width="1486" alt="스크린샷 2024-03-25 오후 5 17 28" src="https://github.com/portone-io/gophplib/assets/7577827/d02493ba-1133-4c4f-9bcc-62df35e81de0">

The values always seem to stay constant once the 'map' is initialized, so presumably they are sorted by some condition, but unfortunately I didn't find anything about this in the release notes or official documentation.

**Comment by simnalamburt** [comment]
See also: https://github.com/portone-io/gophplib/commit/efdbf225c0262ace82fed40a2cd11bbc736b170e
